"""added Account.email column

Revision ID: 176bc9959d70
Revises: 4ddce040328a
Create Date: 2013-07-20 21:44:29.932887

"""

# revision identifiers, used by Alembic.
revision = '176bc9959d70'
down_revision = '4ddce040328a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acct', sa.Column('email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acct', 'email')
    ### end Alembic commands ###
