"""moved use_markdown flag to Revision class

Revision ID: 448f82dea3c4
Revises: 176bc9959d70
Create Date: 2013-09-11 23:01:38.552907

"""

# revision identifiers, used by Alembic.
revision = '448f82dea3c4'
down_revision = '176bc9959d70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', u'use_markdown')
    op.add_column('rev', sa.Column('use_markdown', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rev', 'use_markdown')
    op.add_column('page', sa.Column(u'use_markdown', sa.BOOLEAN(), nullable=False))
    ### end Alembic commands ###
