"""added pw_hash to Account class

Revision ID: 4ddce040328a
Revises: None
Create Date: 2013-07-19 21:08:28.833503

"""

# revision identifiers, used by Alembic.
revision = '4ddce040328a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acct', sa.Column('pw_hash', sa.String()))
    op.drop_column('acct', u'pw')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acct', sa.Column(u'pw', sa.VARCHAR(), nullable=False))
    op.drop_column('acct', 'pw_hash')
    ### end Alembic commands ###
